# Generated by Django 5.0.6 on 2024-06-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_en', models.CharField(max_length=100, null=True, unique=True)),
                ('name_ru', models.CharField(max_length=100, null=True, unique=True)),
                ('name_cs', models.CharField(max_length=100, null=True, unique=True)),
                ('name_uk', models.CharField(max_length=100, null=True, unique=True)),
                ('image', models.ImageField(default='categories/default_bg.jpg', upload_to='categories/')),
                ('background_css', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_ru', models.CharField(max_length=100, null=True)),
                ('name_cs', models.CharField(max_length=100, null=True)),
                ('name_uk', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_cs', models.TextField(null=True)),
                ('description_uk', models.TextField(null=True)),
                ('components', models.TextField()),
                ('components_en', models.TextField(null=True)),
                ('components_ru', models.TextField(null=True)),
                ('components_cs', models.TextField(null=True)),
                ('components_uk', models.TextField(null=True)),
                ('energy', models.TextField()),
                ('energy_en', models.TextField(null=True)),
                ('energy_ru', models.TextField(null=True)),
                ('energy_cs', models.TextField(null=True)),
                ('energy_uk', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
